// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.sap.demo.test_wd1.wd.comp.testcomp.wdp;


/** 
 * This interface provides constants relevant on Web Dynpro Component level
 */
@SuppressWarnings("all")
public interface IConstantTestComp {
}
