// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.sap.demo.test_wd1.wd.comp.testcomp.wdp;



/** 
 * This interface encapsulates all texts / messages for this component. 
 * The message constants of type IWDMessage can be used in
 * conjunction with the IWDMessageManager.reportMessage method.
 * All constants can be used in conjunction with IWDTextAccessor.
 */
@SuppressWarnings("all")
public interface IMessageTestComp {

}
